name: newsdroid
description: Um projeto amador para um app de notícias.

publish_to: 'none'
version: 2.2.0+72
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Auth
  flutter_web_auth_2: ^3.1.1

# Cached Network
  cached_network_image: ^3.3.1

# Connectivity Plus
  connectivity_plus: ^6.0.1

# Crypto
  crypto: ^3.0.3

# Dynamic Colors
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.2

# Firebase
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  firebase_performance: ^0.9.4
  firebase_messaging: ^14.8.0

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Hive  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# HTTP
  http: ^1.2.1

# Intl
  intl: ^0.18.1

# Package Info
  package_info_plus: ^6.0.0

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.2
  
# Review  
  in_app_review: ^2.0.9
  
# Share Plus
  share_plus: ^8.0.2

# Shared Preferences
  shared_preferences: ^2.2.2

# Shimer
  shimmer: ^3.0.0

# Toast
  fluttertoast: ^8.2.4

# Url Launcher
  url_launcher: ^6.2.5

# Widget HTML
  flutter_widget_from_html: ^0.14.11

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/erro/
    - assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
