name: newsdroid
description: Um projeto amador para um app de notícias.

publish_to: 'none'
version: 3.0.4+84
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Auth
  flutter_web_auth_2: ^4.0.0-alpha.5

# Cached Network
  cached_network_image: ^3.3.1

# Chewie
  chewie: ^1.8.1

# Connectivity Plus
  connectivity_plus: ^6.0.3

# Crypto
  crypto: ^3.0.3

# Email
  flutter_email_sender: ^6.0.3

# Firebase
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_performance: ^0.9.4+7

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Hive  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# HTTP
  http: ^1.2.1

# Iconsax
  iconsax: ^0.0.8
  
# Intl
  intl: ^0.19.0

# OneSignal
  onesignal_flutter: ^5.2.0

# Package Info
  package_info_plus: ^8.0.0

# Path Provider
  path_provider: ^2.1.3

# Provider
  provider: ^6.1.2
  
# Review  
  in_app_review: ^2.0.9
  
# Share Plus
  share_plus: ^9.0.0

# Shared Preferences
  shared_preferences: ^2.2.3

# Shimer
  shimmer: ^3.0.0

# Toast
  fluttertoast: ^8.2.5

# Url Launcher
  url_launcher: ^6.2.6

# Widget HTML
  flutter_widget_from_html: ^0.15.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/erro/
    - assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf