name: newsdroid
description: Um projeto amador para um app de notícias.

publish_to: 'none'
version: 3.8.2+20250827

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

# Cached Network
  cached_network_image: ^3.4.1

# Connectivity Plus
  connectivity_plus: ^7.0.0

# Crypto
  crypto: ^3.0.6

# Device Plus
  device_info_plus: ^11.4.0
  
# Dynamic Color
  dynamic_color: ^1.8.1

# Firebase
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  firebase_performance: ^0.11.0

# Google Sign
  google_fonts: ^6.3.0
  google_sign_in: ^6.3.0
  google_mobile_ads: ^6.0.0

# Hive  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# HTML
  html: ^0.15.5+1

# HTTP
  http: ^1.5.0
  
# Intl
  intl: ^0.20.0

# Package Info
  package_info_plus: ^8.3.0

# Permission Handler
  permission_handler: ^12.0.0+1

# Provider
  provider: ^6.1.5
  
# Share Plus
  share_plus: ^12.0.0

# Shared Preferences
  shared_preferences: ^2.5.3

# Shimer
  shimmer: ^3.0.0

# Shorebird
  shorebird_code_push: ^2.0.4

# TTS
  flutter_tts: ^4.2.3

# Url Launcher
  url_launcher: ^6.3.1

# Widget HTML
  flutter_widget_from_html: ^0.17.0

# Wiredash
  wiredash: ^2.5.0
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/erro/
    - assets/img/
    - shorebird.yaml