name: newsdroid
description: Um projeto amador para um app de notícias.

publish_to: 'none'
version: 3.7.0+370

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

# Cached Network
  cached_network_image: ^3.4.1

# Connectivity Plus
  connectivity_plus: ^6.1.2

# Crypto
  crypto: ^3.0.6

# Device Plus
  device_info_plus: ^11.2.2
  
# Dynamic Color
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.3

# Firebase
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  firebase_performance: ^0.10.1+1

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: 5b2c7ae

# Google Sign
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2

# Hive  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# HTML
  html: ^0.15.5

# HTTP
  http: ^1.3.0
  
# Intl
  intl: ^0.19.0

# OneSignal
  onesignal_flutter: ^5.2.9

# Package Info
  package_info_plus: ^8.1.4

# Path Provider
  path_provider: ^2.1.5

# Permission Handler
  permission_handler: ^11.3.1

# Provider
  provider: ^6.1.2
  
# Review  
  in_app_review: ^2.0.10
  
# Share Plus
  share_plus: ^10.1.4

# Shared Preferences
  shared_preferences: ^2.5.1

# Shimer
  shimmer: ^3.0.0

# Shorebird
  shorebird_code_push: ^2.0.2

# TTS
  flutter_tts: ^4.2.2

# Url Launcher
  url_launcher: ^6.3.1

# Widget HTML
  flutter_widget_from_html: ^0.15.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/erro/
    - assets/img/
    - shorebird.yaml