name: newsdroid
description: Um projeto amador para um app de notícias que usa WebView.

publish_to: 'none'
version: 1.0.14+32

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_inappwebview: ^6.0.0-beta.23
  connectivity_plus: ^4.0.1
  onesignal_flutter: ^3.5.1
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_performance: ^0.9.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/erro/

  fonts:
  - family: OpenSans
    fonts:
    - asset: fonts/opensans/OpenSans-Regular.ttf
    - asset: fonts/opensans/OpenSans-Light.ttf
    - asset: fonts/opensans/OpenSans-Bold.ttf
      weight: 900
    - asset: fonts/opensans/OpenSans-Medium.ttf
      weight: 300
    - asset: fonts/opensans/OpenSans-SemiBold.ttf
      weight: 500
    - asset: fonts/opensans/OpenSans-Italic.ttf
      style: italic

