name: newsdroid
description: Um projeto amador para um app de notícias que usa WebView.

publish_to: 'none'
version: 1.0.17+35

environment:
  sdk: '>=3.0.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_inappwebview: ^6.0.0-beta.24+1
  connectivity_plus: ^4.0.1
  onesignal_flutter: ^3.5.1
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/erro/
