name: newsdroid
description: Um projeto amador para um app de notícias.

publish_to: 'none'
version: 2.0.6+68
environment:
  sdk: '>=3.0.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Auth
  flutter_web_auth_2: ^3.1.1

# Cached Network
  cached_network_image: ^3.3.1

# Connectivity Plus
  connectivity_plus: ^5.0.2

# Crypto
  crypto: ^3.0.3

# Dynamic Colors
  dynamic_color: ^1.6.9

# Email
  flutter_email_sender: ^6.0.2

# FAB
  flutter_expandable_fab: ^2.0.0

# Firebase
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  firebase_messaging: ^14.7.10

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Hive  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# HTTP
  http: ^1.2.0

# Intl
  intl: ^0.18.1

# Modal Bottom Sheet
  modal_bottom_sheet: ^3.0.0-pre

# Package Info
  package_info_plus: ^5.0.1

# Path Provider
  path_provider: ^2.1.2

# Provider
  provider: ^6.1.1
  
# Share Plus
  share_plus: ^7.2.1

# Shared Preferences
  shared_preferences: ^2.2.2

# Shimer
  shimmer: ^3.0.0

# Toast
  fluttertoast: ^8.2.4

# Url Launcher
  url_launcher: ^6.2.4

# Widget HTML
  flutter_widget_from_html: ^0.14.11

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/erro/
    - assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
